# Generated by Django 5.2.1 on 2025-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_article_categories_article_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
