# Generated by Django 5.2.1 on 2025-06-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_article_image_article_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='couleur',
            field=models.CharField(blank=True, help_text='Code couleur hexadécimal, ex: #007cba', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='icone',
            field=models.CharField(blank=True, help_text="Nom de l'icône ou code SVG", max_length=100, null=True),
        ),
    ]
