# Generated by Django 5.2.1 on 2025-06-04 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_categorie_couleur_categorie_icone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InteractionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('vue', 'Vue'), ('like', "J'aime"), ('commentaire', 'Commentaire'), ('partage', 'Partage')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('date_interaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('temps_lecture', models.PositiveIntegerField(blank=True, help_text='Temps passé en secondes', null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_interaction'],
                'unique_together': {('utilisateur', 'article', 'type_interaction', 'session_key')},
            },
        ),
    ]
