# Generated by Django 5.2.1 on 2025-06-04 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_vues_interactionutilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lecteur', 'Lecteur'), ('redacteur', 'Rédacteur'), ('moderateur', 'Modérateur'), ('editeur', 'Éditeur'), ('administrateur', 'Administrateur')], default='lecteur', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('banni', 'Banni')], default='actif', max_length=20)),
                ('bio', models.TextField(blank=True, help_text="Biographie de l'utilisateur", null=True)),
                ('avatar', models.TextField(blank=True, help_text='Avatar en base64', null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('nombre_articles', models.PositiveIntegerField(default=0)),
                ('nombre_commentaires', models.PositiveIntegerField(default=0)),
                ('notifications_email', models.BooleanField(default=True)),
                ('notifications_nouveaux_articles', models.BooleanField(default=True)),
                ('notifications_commentaires', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'permissions': [('can_moderate_comments', 'Peut modérer les commentaires'), ('can_manage_categories', 'Peut gérer les catégories'), ('can_publish_articles', 'Peut publier des articles'), ('can_edit_all_articles', 'Peut éditer tous les articles'), ('can_view_statistics', 'Peut voir les statistiques'), ('can_manage_users', 'Peut gérer les utilisateurs')],
            },
        ),
    ]
